# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a0c485740dd778b1891891607bfd4b64"
application_url = "https://phpstack-362288-5094532.cloudwaysapps.com"
embedded = true
name = "Conversion-king"
handle = "conversion-king-live"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_orders,read_orders,write_locations,read_locations,write_inventory,read_inventory,write_publications,read_publications,write_discounts,read_discounts,write_customers,read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://phpstack-362288-5094532.cloudwaysapps.com/auth/callback",
  "https://phpstack-362288-5094532.cloudwaysapps.com/auth/shopify/callback",
  "https://phpstack-362288-5094532.cloudwaysapps.com/api/auth/callback"
]

[app_proxy]
url = "https://phpstack-362288-5094532.cloudwaysapps.com/api"
subpath = "view"
prefix = "a"

[pos]
embedded = false

[build]
dev_store_url = "conversion-king-x.myshopify.com"
automatically_update_urls_on_dev = true
include_config_on_deploy = true
