# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "838e074fbf5dc10b75f771c5cec3053d"
application_url = "https://lucy-overcome-bras-geography.trycloudflare.com"
embedded = true
name = "Conversion-king"
handle = "conversion-king-1"

[webhooks]
api_version = "2024-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,write_orders,read_orders,write_locations,read_locations,write_inventory,read_inventory,write_publications,read_publications,write_discounts,read_discounts,write_customers,read_customers"
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://lucy-overcome-bras-geography.trycloudflare.com/auth/callback",
  "https://lucy-overcome-bras-geography.trycloudflare.com/auth/shopify/callback",
  "https://lucy-overcome-bras-geography.trycloudflare.com/api/auth/callback"
]

[app_proxy]
url = "https://lucy-overcome-bras-geography.trycloudflare.com/api"
subpath = "view"
prefix = "a"

[pos]
embedded = false

[build]
dev_store_url = "junaidamjad936.myshopify.com"
automatically_update_urls_on_dev = true
